# Generated by Django 2.2.10 on 2021-09-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercices', '0003_exercices_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercices',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exercices',
            name='regime',
            field=models.CharField(default=323, max_length=200),
            preserve_default=False,
        ),
    ]
