# Generated by Django 2.2.10 on 2021-09-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('societ', '0008_societe_nom'),
        ('exercices', '0005_remove_exercices_societe'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercices',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='societ.Societe'),
        ),
    ]
