# Generated by Django 2.2.10 on 2021-09-05 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('raisonSocial', models.CharField(max_length=200)),
                ('iff', models.CharField(max_length=200)),
                ('ice', models.CharField(max_length=200)),
                ('tp', models.CharField(max_length=200)),
                ('rc', models.CharField(max_length=200)),
                ('cnss', models.CharField(max_length=200)),
                ('formJuridique', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('regime', models.CharField(max_length=200)),
                ('commune', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='soicetesLogos')),
            ],
        ),
        migrations.CreateModel(
            name='simpleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('societe', models.ManyToManyField(to='societ.Societe')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'simpleUser',
            },
        ),
    ]
