# Generated by Django 2.2.10 on 2021-09-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societ', '0002_auto_20210908_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societe',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
