# Generated by Django 2.2.10 on 2021-09-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societ', '0003_auto_20210908_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societe',
            name='profile_pic',
        ),
        migrations.AlterModelTable(
            name='simpleuser',
            table=None,
        ),
    ]
