# Generated by Django 2.2.10 on 2021-09-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societ', '0004_auto_20210911_1811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='simpleUser',
        ),
    ]
