# Generated by Django 2.2.10 on 2021-09-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societ', '0005_delete_simpleuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societe',
            name='model',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='regime',
        ),
    ]
