# Generated by Django 2.2.10 on 2021-09-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societ', '0006_auto_20210923_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='cni',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='societe',
            name='prenom',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='societe',
            name='tel',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
