# Generated by Django 2.2.10 on 2021-09-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societ', '0007_auto_20210923_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='nom',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
