# Generated by Django 2.2.10 on 2021-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societ', '0008_societe_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
