# Generated by Django 2.2.10 on 2021-09-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='société',
            table='société',
        ),
    ]
