# Generated by Django 2.2.10 on 2021-09-25 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('societ', '0008_societe_nom'),
        ('exercices', '0004_auto_20210923_1708'),
        ('encaissements', '0003_remove_encaissements_prorata'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaissements',
            name='periode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercices.Exercices'),
        ),
        migrations.AddField(
            model_name='encaissements',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='societ.Societe'),
        ),
    ]
